### PR TITLE
Add more complete ubuntu build instructions

### PR DESCRIPTION
**Pull request by ianhi**
Puts them all together in one place so it's easier, also added using conda-forge for getting swig rather than compiling it yourself.

### CODE REVIEW

**Comment by ianhi** [comment]
Although as a not so fun fact. This worked the first time I opened it, but on subsequent times it is failing wiht this error:

```
2022-03-18T12:04:04.439491 tid140562641831488 [IFO,App] User: ian
2022-03-18T12:04:04.439513 tid140562641831488 [IFO,App] Host: fermented-beans
2022-03-18T12:04:04.439525 tid140562641831488 [IFO,App] MM Studio version: 2.0.x dev
2022-03-18T12:04:04.439553 tid140562641831488 [IFO,App] MMCore version 10.2.0
2022-03-18T12:04:04.439570 tid140562641831488 [IFO,App] Device API version 70, Module API version 10
2022-03-18T12:04:04.439582 tid140562641831488 [IFO,App] Operating System: Linux (amd64) 5.15.23-76051523-generic
2022-03-18T12:04:04.439593 tid140562641831488 [IFO,App] JVM: OpenJDK 64-Bit Server VM, version 17.0.2, 64-bit
2022-03-18T12:04:16.840537 tid140562641831488 [IFO,App] Finished waiting for plugins to load
2022-03-18T12:04:17.052742 tid140562641831488 [IFO,App] Thread 1 (main) terminated with uncaught exception
2022-03-18T12:04:17.052921 tid140562641831488 [IFO,App] java.lang.NullPointerException: Cannot invoke "java.awt.GraphicsConfiguration.getBounds()" because "config" is null
2022-03-18T12:04:17.052955 tid140562641831488 [IFO,App]   at org.micromanager.internal.dialogs.IntroDlg.<init>(IntroDlg.java:216)
2022-03-18T12:04:17.052959 tid140562641831488 [IFO,App]   at org.micromanager.internal.MMStudio.<init>(MMStudio.java:370)
2022-03-18T12:04:17.052962 tid140562641831488 [IFO,App]   at org.micromanager.internal.MMStudio.main(MMStudio.java:195)

```

**Comment by ianhi** [comment]
Those errors come from: https://github.com/micro-manager/micro-manager/blob/47298d8df3a3c8013a900e5d7274a8c7e46948a7/mmstudio/src/main/java/org/micromanager/internal/dialogs/IntroDlg.java#L215-L216

**Comment by ianhi** [comment]
This is happening depending on whether I have an external monitor plugged in: https://github.com/micro-manager/micro-manager/issues/1427

**Comment by ianhi** [comment]
Updated to instructions to what brought me to the most working setup. Still can't launch with multi monitors, and there are some styling issues, but mostly it works.

**Comment by marktsuchida** [comment]
Looks good overall.

The `mamba` and `conda` commands are alien to most Java or C++ developers, so it would be nice to add a comment line before them to briefly state that they do.

Perhaps more importantly, the instructions (or at least URLs) for installing those commands is missing.

Also, the `curl` to fetch iconloader should be run _before_ `make fetchdeps` and it should place the jar at `../3rdpartypublic/classext`, so that Ivy can move it into `dependencies/artifacts`. Placing it directly into `dependencies` is fragile. Probably best to place the command just after the Git checkout. I guess you can remove `subversion` from `apt-get install` in these instructions.

**Comment by ianhi** [comment]
> The mamba and conda commands are alien to most Java or C++ developers, so it would be nice to add a comment line before them to briefly state that they do.
> 
> Perhaps more importantly, the instructions (or at least URLs) for installing those commands is missing.

Good point, will do.

> should be run before make fetchdeps and it should place the jar at ../3rdpartypublic/classext, so that Ivy can move it into dependencies/artifacts. Placing it directly into dependencies is fragile. Probably best to place the command just after the Git checkout

interesting. I got that from the very bottom of the file which says:

"Take a look at https://github.com/micro-manager/micro-manager/issues/708 and https://github.com/micro-manager/micro-manager/issues/837. You may need DT1.2,jxinput, iconloader from original [svn site](https://valelab4.ucsf.edu/svn/3rdpartypublic/classext/). You should not run make fetchdeps again after you copied jar files to dependencies/artifacts/compile, otherwise make fetchdeps will remove copyed files."

I suppose that should be changed as well?

**Comment by marktsuchida** [comment]
> I got that from the very bottom of the file which says:
> 
> "Take a look at #708 and #837. You may need DT1.2,jxinput, iconloader from original [svn site](https://valelab4.ucsf.edu/svn/3rdpartypublic/classext/). You should not run make fetchdeps again after you copied jar files to dependencies/artifacts/compile, otherwise make fetchdeps will remove copyed files."
> 
> I suppose that should be changed as well?

I think that entire section ("Failing to fetch on Ubuntu 18.04 and newer") is now okay to delete. The JOGL/gluegen issues have been solved by recent updates and those are no longer fetched from `3rdpartypublic`. `DT1.2` and `jxinput` are in `3rdpartypublic` just like `iconloader` (see below). Nothing here is specific to Ubuntu 18+; it is common to all failures of `make fetchdeps` on any Unix.

The instructions always said you had to have the full `3rdpartypublic` next to `micro-manager`. I guess the author of those comments missed that.

These days it probably makes sense to fetch a minimal subset or `3rdpartypublic` (except on Windows). I would need to check to be 100% sure, but I don't think the macOS/Linux builds ever use anything in `3rdpartypublic` outside of `classext` (they certainly don't require anything, as you have already found). One possibility would be to fetch `iconloader`, `DT1.2`, and `jxinput`, but this is ugly.

Perhaps a better way is to fetch just the `classext` directory. This can be done with the `svn` command:
```
mkdir 3rdpartypublic; cd 3rdpartypublic
svn checkout https://valelab4.ucsf.edu/svn/3rdpartypublic/classext
```
This only takes up 38 MiB.

**Comment by ianhi** [comment]
> Perhaps a better way is to fetch just the classext directory. This can be done with the svn command:
> 
> mkdir 3rdpartypublic; cd 3rdpartypublic
> svn checkout https://valelab4.ucsf.edu/svn/3rdpartypublic/classext

> This only takes up 38 MiB.


this still failed on iconloader for me, it doesn't seem to end up in `dependencies/artifacts/compile`

**Comment by marktsuchida** [comment]
It should copy from `../3rdpartypublic/classext/iconloader.jar` to `dependencies/artifacts/compile/iconloader-GIT.jar` (just did a quick check on macOS). But Ivy (the dependency resolver) caches jars, so maybe try `rm -r ~/.ivy2/cache/iconloader/` before rerunning `make fetchdeps`.

**Comment by ianhi** [comment]
> But Ivy (the dependency resolver) caches jars, so maybe try rm -r ~/.ivy2/cache/iconloader/ before rerunning make fetchdeps.

nope didn't seem to do it :(

`ls dependencies/artifacts/compile/`
gives

```
AcqEngJ-0.13.0.jar           gluegen-rt-2.3.2.jar                           jxrlib-all-0.2.1.jar
activation-1.1.jar           gluegen-rt-2.3.2-natives-linux-amd64.jar       kryo-2.24.0.jar
AppleJavaExtensions-1.4.jar  gluegen-rt-2.3.2-natives-linux-i586.jar        logback-classic-1.1.1.jar
args4j-2.0.29.jar            gluegen-rt-2.3.2-natives-macosx-universal.jar  logback-core-1.1.1.jar
badtrack-0.1.4.jar           gluegen-rt-2.3.2-natives-windows-amd64.jar     mail-1.5.0-b01.jar
bio-formats-tools-5.5.3.jar  gluegen-rt-2.3.2-natives-windows-i586.jar      metadata-extractor-2.6.2.jar
boofcv-geo-0.36.jar          gluegen-rt-main-2.3.2.jar                      metakit-5.3.0.jar
boofcv-ip-0.36.jar           gson-2.2.4.jar                                 miglayout-3.7.4.jar
boofcv-types-0.36.jar        guava-17.0.jar                                 miglayout-core-4.2.jar
bridj-0.7.0.jar              hamcrest-core-1.3.jar                          miglayout-swing-4.2.jar
bsh-2.0b6.jar                imagej-common-0.26.1.jar                       minlog-1.2.jar
caffeine-2.4.0.jar           imglib2-5.6.3.jar                              native-lib-loader-2.1.4.jar
clearaudio-1.0.2.jar         imglib2-cache-1.0.0-beta-9.jar                 nativelibs4java-utils-1.6.jar
clearcl-0.5.2.jar            imglib2-realtransform-2.0.0.jar                NDTiffStorage-2.4.8.jar
clearcl-0.6.0.jar            imglib2-roi-0.5.2.jar                          NDViewer-0.5.3.jar
cleargl-2.2.6.jar            jai_imageio-5.5.3.jar                          netcdf-4.3.22.jar
clearvolume-1.4.1.jar        jama-1.0.3.jar                                 objenesis-2.1.jar
clojure-1.3.0.jar            javacl-1.0.0-RC4.jar                           ome-common-5.3.1.jar
commons-io-2.11.0.jar        javacl-core-1.0.0-RC4.jar                      ome-mdbtools-5.3.0.jar
commons-lang-2.6.jar         jcommon-1.0.24.jar                             ome-poi-5.3.1.jar
commons-lang3-3.5.jar        jeromq-0.5.1.jar                               ome-xml-5.1.1.jar
commons-logging-1.1.1.jar    jfreechart-1.5.0.jar                           ome-xml-5.5.4.jar
commons-math-2.2.jar         jgoodies-common-1.7.0.jar                      opencl4java-1.0.0-RC4.jar
commons-math3-3.6.1.jar      jgoodies-forms-1.7.2.jar                       parsington-1.0.3.jar
core.cache-0.6.2.jar         jhdf5-14.12.0.jar                              perf4j-0.9.13.jar
coremem-0.4.5.jar            jitk-tps-3.0.2.jar                             protobuf-java-2.6.1.jar
core.memoize-0.5.2.jar       jna-4.5.1.jar                                  PycroManagerJava-0.24.1.jar
data.json-0.1.1.jar          jnacl-1.0.0.jar                                rsyntaxtextarea-2.6.1.jar
ddogleg-0.18.jar             jna-platform-4.5.1.jar                         scifio-0.37.3.jar
dx-1.7.jar                   jocl-2.0.1.jar                                 scifio-jai-imageio-1.1.1.jar
ejml-cdense-0.39.jar         joda-time-2.2.jar                              scijava-common-2.77.0.jar
ejml-core-0.39.jar           jogl-all-2.3.2.jar                             serializer-2.7.2.jar
ejml-ddense-0.39.jar         jogl-all-2.3.2-natives-linux-amd64.jar         slf4j-api-1.7.30.jar
ejml-dsparse-0.39.jar        jogl-all-2.3.2-natives-linux-i586.jar          specification-5.5.4.jar
ejml-fdense-0.39.jar         jogl-all-2.3.2-natives-macosx-universal.jar    trove4j-3.0.3.jar
ejml-fsparse-0.39.jar        jogl-all-2.3.2-natives-windows-amd64.jar       turbojpeg-5.5.3.jar
ejml-simple-0.39.jar         jogl-all-2.3.2-natives-windows-i586.jar        udunits-4.3.18.jar
ejml-zdense-0.39.jar         jogl-all-main-2.3.2.jar                        vecmath-1.5.2.jar
eventbus-1.4.jar             jogl-all-main-2.3.2-javadoc.jar                xalan-2.7.2.jar
formats-api-5.5.3.jar        jogl-all-main-2.3.2-sources.jar                xercesImpl-2.8.1.jar
formats-bsd-5.5.3.jar        jsr250-api-1.0.jar                             xml-apis-1.3.04.jar
formats-common-5.1.1.jar     jsr305-3.0.2.jar                               xmpcore-5.1.2.jar
formats-gpl-5.5.3.jar        junit-4.12.jar
georegression-0.22.jar       JWlz-1.4.0.jar
```

**Comment by marktsuchida** [comment]
Just tested on Ubuntu 20.04 and it works for me. I had no `~/.ivy2` and started with a clean clone of `micro-manager`.
`3rdpartypublic/classext` was checked out as above, such that `3rdpartypublic` and `micro-manager` were in the same directory.

**Pull request merged**
