### PR TITLE
Added Basler Ace Device Adapter

### PR DESCRIPTION
**Pull request by henrypinkard**
Device adapter for Basler Ace USB Monochrome machine vision cameras

### CODE REVIEW

**Comment by marktsuchida** [comment]
Thanks, @henrypinkard. I know a lot of people will be happy to see Basler cameras supported!

I will be committing this to 1.4 SVN.

Would be wonderful if you could
- Fix indents to be uniform (3 spaces preferred)
- Remove commented code and nonstandard items in the project (copy command and reference to bitflow SDK)
- Include the `.vcxproj.filters` file (unlike `.vcxproj.user`, it's part of the project definition)
- Ensure copyright is correct
- Avoid initializing the library in `CreateDevice()` and accessing the library from the device constructor. Both of these should be done in `Initialize()` so that errors can be returned.
- As currently written, µManager will likely crash or misbehave if the user attempts to create a second camera. Best if you could ensure that `Initialize()` returns an error _before_ calling `PylonInitialize()` a second time (as long as multiple cameras are not supported), and that `PylonTerminate()` is called in `Shutdown()`, only if `PylonInitialize()` was called by the same camera device object.
- Ok, I take that last point back - I was just skimming the Basler release notes and apparently `PylonInitialize` and `PylonTerminate` are reference counted (since their latest version), so no need to do that ourselves. Still would be nice to call in `Initialize`/`Shutdown`, though.

The only other question is (and I hate to bring this up), do you know how/whether Pylon provides _binary_ compatibility across different versions? This can cause a gigantic headache with C++ (not C) interfaces. It's not a problem if Basler allows its DLLs to be redistributed so that users don't have to find an exact matching driver version (_and_ their size is reasonable so that they won't bloat the µManager installer). It may also not be a problem if Basler has done some magic in their library interface so that binary compatibility is maintained between their versions. I'll look into this when I have a chance, but let me know if you've spotted any mention of this in their documentation. If this does turn out to be an issue, the only practical solution might be to rewrite using their C interface, but I won't ask you to do that before merging this :).

**Comment by jondaniels** [comment]
@henrypinkard, @marktsuchida: There have been posts on the mailing list about this device adapter, e.g. http://micro-manager.3463995.n2.nabble.com/Micro-manager-adapter-for-BASLER-USB3-camera-td7589466.html.  I bring this up just to say there are multiple people hoping this will incorporated into the nightly builds, though I claim zero personal interest.

**Comment by henrypinkard** [comment]
Hi @jondaniels ,
Good to know, thanks. This has been on my ToDo list for a while--hopefully I can get to it in the next week or two

**Comment by marktsuchida** [comment]
@henrypinkard appreciate it!

**Comment by henrypinkard** [comment]
@marktsuchida in response to your previous comments:

- I've fixed the copyright/nonstandard items in project/and indentation
- This project doesn't have a `.vcxproj.filters` file itself. I've been building it by adding it to `MMCoreJ_wrap`. Do you want me to commit the changed `MMCoreJ_wrap.vxcproj.filters`?
- Moved the initialization code into `Initialize`/`Shutdown`
- No idea about the binary compatibility issue

**Comment by bjudkewitz** [comment]
@marktsuchida and @henrypinkard, I can confirm that many people are eagerly waiting for this to be merged with the master branch. Thanks a lot for working on this!

**Comment by melaniegraesel** [comment]
@marktsuchida  and @henrypinkard , since the last post is from end of august and as far as I know the Basler ace isn't implemented yet, I wanted to push this topic again. When do you think the device adapter will be available? I'm looking forward for this! Thank you very much and best regards.

**Comment by nicost** [comment]
Source code added to the subversion repository in revision r16809.  Not in build yet.

**Comment by bryantChhun** [comment]
Has anyone tried testing this code on multiple Basler cameras?  We can't get the hardware config wizard to load a second Basler using the same device adapter as the first (compiled from this code in this PR).  I can post more details, thought to reach out in case there's a quick answer.

**Comment by henrypinkard** [comment]
I only had access to one when I was developing. I'm almost positive it's possible to do multiple at once with the Basler API, but it might require some small modifications to the code

**Comment by bryantChhun** [comment]
We are able to use multiple Baslers using their API and their code, just not through micromanager.

What we've done so far, and does not quite work, is follow Basler's "grab_multipleCameras" example.  In the Initialize(), I tried calling:
`CTlFactory::GetInstance().CreateDevice( devices[index])`
rather than
`CTlFactory::GetInstance().CreateFirstDevice()`
where devices is a DeviceInfoList_t property.  I also use a static property to increment the device index.  Two cameras can be added into the hardware config wizard (does it initialize here?), but crashes mm2.0 with "abnormal termination error" after the config is saved and returns to the main GUI.

I can post some logs here if you like.  Or, maybe wait a day first to see if there's a solution tomorrow :-)

**Comment by ryandoobs8** [comment]
How/where do you add the files to MicroManager to be able to access Basler Ace cameras?  I downloaded the three codes, but am unsure of where they should reside for MicroManager to reference them.

Thank you in advance.

**Comment by StudDavid** [comment]
Hi, 
I am also highly interested in the integration of the Basler Ace into MicroManager. I tried to paste a .dll with the code of @henrypinkard into the MicroManager files. Got the Basler camerea listed under hardware (unavailable) in MM afterwards. Furthermore tried using the 2.0 beta version and the 2.0- gamma version of MM. Both didnt solve the problem, that the camera doesnt show up. Maybe @bryantChhun could provide more information on how to integrate the BaserAce?

**Comment by SMA2016a** [comment]
Hi StudDavid,

simply download this files and copy either  X64 or X32 dll into the mm directory. 
micro-manager-ViewerPlusCV_MMSetup_64bit_2.0.0-gamma1_20190213.zip  

You should also use the latest version of mm MMSetup_64bit_2.0.0-gamma1_20190213.exe 

Then it should work.  this dll supports more pixel format than the previous  dll "BaserAce"

**Comment by SMA2016a** [comment]
https://www.sendspace.com/file/dwlqfc

**Comment by SMA2016a** [comment]
Hi [bryantChhun](/bryantChhun) 

if you wanted use device index then you also take care for calling retrieve result for each camera.  
CTlFactory::GetInstance().CreateDevice( devices[index])

after I have finish the binning function then can add multiple camera support if there is reasonable demand for that.

**Comment by henrypinkard** [comment]
@StudDavid That error is generally a mismatch between the version of micromanager that the DLL was compiled for and the version of MM you are using. If you look in the micromanager corelogs (directory in the install folder) you can figure out if you need an older or newer version of a mm nightly build to match your device adater

**Comment by henrypinkard** [comment]
@SMA2016a Great that you have added these improvements! Do you have a branch off my `[basler](/henrypinkard/micro-manager/tree/basler)` branch of [henrypinkard/micro-manager](/henrypinkard/micro-manager). that I could use to test it still works on the original camera I developed? That way we could get everything in a single project and maybe even add it to the build so people wouldn't have to install manually

**Comment by nicost** [comment]
This is all very confusing to me.  The BaselAce device adapter by Ravi (based on Henry's code) was added to the repository about two weeks ago (https://valelab4.ucsf.edu/svn/micromanager2/trunk/DeviceAdapters/Basler/).  I still have not been told whether it actually works as intended or not.  I don't know if @SMA2016a is the same person as Ravi or not (and hence whether this is yet another version of a BaslerPylon adapter or nor).  In general, please don't share binaries, just contribute your code and work from a central place.  Please figure out if the code in the repository works or not, provide installation instructions on the Micro-Manager website (https://micro-manager.org/wiki/BaslerAce) and be done with it.

**Comment by henrypinkard** [comment]
@nicost I've been unable to test the changes as I lost access to a BaslerAce after developing the adapter, but our lab just got another one so I can test these new changes now. Has Basler been added to the nightly builds yet? Finally, is it okay to add device adapters through GitHub or is it all still on subversion? I was unable to find any Basler Code on micro-manager/master

**Comment by nicost** [comment]
Yes, the adapter is in the nightly builds (or should be, I am too lazy to actually look and get confusing signals from users).  The master "copy" of Device Adapters in the Micro-Manager eco-system is still the subversion repository on the valelab server.  Things are copied from there.  micro-manager/master on github is a dead branch, svn is now copied to the branch svn-mirror.  It is simplest to work directly with the subversion repository for devices.  Email me new adapters, I will add them in and give you write access.  mm2-gamma (source on nicost/micro-manager ViewerPlusCV branch) stays quite up to date with subversion device adapters, other branches do not.

**Comment by SMA2016a** [comment]
Hi Nico,

 

yes, sma2016a is me.

 

Ok, I will not distriebute binary any more. 

 

THe current version of BaslerPylon5Camera.cpp  is fully tested with GigE and USB Cameras.

 

I am working on Binning, as soon as I finish it, I will send you an update.

 

Best reggards,

Ravi

 

 




-----Ursprüngliche Nachricht-----
 Von: "Nico Stuurman" [notifications@github.com]
 Gesendet: Do. 14.02.2019 23:39
 An: "micro-manager/micro-manager" [micro-manager@noreply.github.com]
 Kopie: "SMA2016a" [ssnet@freenet.de],  "Mention" [mention@noreply.github.com]
 Betreff: Re: [micro-manager/micro-manager] Added Basler Ace Device Adapter (#620)





This is all very confusing to me.  The BaselAce device adapter by Ravi (based on Henry's code) was added to the repository about two weeks ago (https://valelab4.ucsf.edu/svn/micromanager2/trunk/DeviceAdapters/Basler/).  I still have not been told whether it actually works as intended or not.  I don't know if @SMA2016a is the same person as Ravi or not (and hence whether this is yet another version of a BaslerPylon adapter or nor).  In general, please don't share binaries, just contribute your code and work from a central place.  Please figure out if the code in the repository works or not, provide installation instructions on the Micro-Manager website (https://micro-manager.org/wiki/BaslerAce) and be done with it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.





-----Ursprüngliche Nachricht Ende-----

**Comment by henrypinkard** [comment]
@SMA2016a Hi Ravi, if you send me your code when you finish it (hbp [at] berkeley.edu) I could verify that it still works on the original Basler I developed the adapter on then we could combine everything into a single device adapter, which would simplify things for users (if @nicost is okay with this plan)

**Comment by nicost** [comment]
Ravi, just submit directly to the subversion repository (I already asked you before if you want an account there).  Henry, just test the Micro-Manager builds and provide feedback.  Otherwise we will stay in version/build hell! Also, much easier to keep these kind of discussions on the mailing list (would have avoided a lot of confusion).

**Comment by StudDavid** [comment]
Hello again,
I can confirm that with the .dll provided by @SMA2016a the Basler Ace camera works great with the latest version of mm2-gamma. Thanks to everybody for replying so quickly. I'll also try the nightly build of MM tomorrow.

**Comment by nicost** [comment]
The same code should be in the latest nightly build.  Please do confirm if it works as expected.

**Comment by StudDavid** [comment]
@nicost just tried the Basler Ace with the nightly build of MM (19.02) and it works perfectly. BaslerAce is listed in the Hardware options and is fully functional.

**Comment by SMA2016a** [comment]
Thanks for the feedback

 




-----Ursprüngliche Nachricht-----
 Von: "StudDavid" [notifications@github.com]
 Gesendet: Mi. 20.02.2019 12:16
 An: "micro-manager/micro-manager" [micro-manager@noreply.github.com]
 Kopie: "SMA2016a" [ssnet@freenet.de],  "Mention" [mention@noreply.github.com]
 Betreff: Re: [micro-manager/micro-manager] Added Basler Ace Device Adapter (#620)





@nicost just tried the Basler Ace with the nightly build of MM (19.02) and it works perfectly. BaslerAce is listed in the Hardware options and is fully functional.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.





-----Ursprüngliche Nachricht Ende-----

**Comment by henrypinkard** [comment]
@nicost Basler device adapter doesn't appear to be in 2019 02 19 nightly, but adding in Ravis dll works with the camera I originally developed on. So his code can replace my original code, and it can all be kept in a single device adapter to avoid confusion

**Comment by nicost** [comment]
Which Micro-Manager version did you look at?  1.4 and 2.0-gamma should have it, 2.0-beta should not. The code is in a single device adapter and my build logs show no problem (for 1.4 and 2.0-gamma).

**Comment by henrypinkard** [comment]
Ah, I was looking at 2.0-beta. Looks like this is all set then

**Pull request closed without merging**
