### PR TITLE
Incorporate AcqEngJ into MMStudio

### PR DESCRIPTION
**Pull request by henrypinkard**
https://github.com/micro-manager/micro-manager/issues/1465

I've got a preliminary version working and am able to run some basic types of MDAs through the GUI. There's a new option to turn on and off AcqEngJ backend. This shouldn't affect anything the clojure engine is doing, so I would think it can be merged in not too long and tested and improved from there. However, it would be helpful if you could have a look @nicost and @marktsuchida to ensure that I haven't accidentally introduced unintended consequences for those that haven't checked the box.

There are corresponding changes to AcqEngJ and some other deps that should be merged simultaneously with this.

### Some implementation questions:
- [ ]  AcqEngJ has multiple places to hook in code to run either on the thread where acquisition events come from or on the acquistion thread itself (before the stage/channels get set, after they get set but before the camera is activated, or after the camera is activated). Any idea which of these time points the `attachRunnable` interface should be mapped to?
- [ ]  What is supposed to be happening with autoshutter--I've always been confused about this
- [ ] The position list: is the acquisition engine supposed to move multiple XY stages if they're both defined in the position list, or just the main one? 
- [ ] Should Z positions in the position list have any effect?
- [ ]  Autofocus: I haven't attempted to put this in yet. What is the correct behavior? I'm not especially familiar with how AF in MM is supposed to work
- [ ]  Any knowledge of what metadata tags are required? The metadata requirements are a huge mess as there are many hidden tags required in different parts of the software and as far as I know the minimal set is not documented anywhere. I remember some of the requirements, and the rest I've been slowly figuring out empirically by copying the clojure engine's output (which is hard, because there don't seem to be any exceptions when they're missing). Any additional knowledge would help this process
- [ ]  any objections to me deleting the [Clojure stuff](https://micro-manager.org/Clojure) on the website now? And maybe cleaning up [this page ](https://micro-manager.org/Multi-Dimensional_Acquisition_Programming) on MDA programming which appears to be outdated?

### CODE REVIEW

**Comment by marktsuchida** [comment]
I'll try to look at the code in the coming days, but here are quick answers to your questions:

> * [ ]   AcqEngJ has multiple places to hook in code to run either on the thread where acquisition events come from or on the acquistion thread itself (before the stage/channels get set, after they get set but before the camera is activated, or after the camera is activated). Any idea which of these time points the `attachRunnable` interface should be mapped to?

The Clojure engine calls the runnable before opening the shutter for a snap, after most other changes have finished. However, I vaguely remember that it can overlap with something. Only the code has the true answer.

> * [ ]   What is supposed to be happening with autoshutter--I've always been confused about this

Autoshutter means that the current `Core`-`Shutter` is opened before a snap or sequence, and is closed when the snap or sequence finishes. If autoshutter is off, `Core`-`Shutter` is ignored. (Not sure what your question is about?)

> * [ ]  The position list: is the acquisition engine supposed to move multiple XY stages if they're both defined in the position list, or just the main one?

I think so, and also for multiple Z stages. This should be easy to test.

> * [ ]  Should Z positions in the position list have any effect?

Yes. They specify the Z position of the acquisition for that position. Aside from manually focusing on different positions, this is also used by the 3-point focus plane generated by the HCS site generator.

If autofocus is enabled (at least under certain conditions), I believe they specify the initial starting point for focusing. When a second image is taken at the same XY position, the computed focus from the previous round is used as the starting point (this Z position memory is internal to the acqEngine).

> * [ ]   Autofocus: I haven't attempted to put this in yet. What is the correct behavior? I'm not especially familiar with how AF in MM is supposed to work

It's very complicated with lots of case logic, and I don't think there is much hope of correctly replicating it without studying the existing code. Yet, changing the behavior without notice would break a lot of people's workflow. I can try and help (e.g. happy to study the code together), but I can't answer this off the top of my head.

This is probably the bulk of the hard-coded complexity of acqEngine aside from hardware triggering, but I don't think it is an unsolvable problem. acqEngine actually hard-codes behavior that is not always the most desirable, so having the new engine be capable of a superset of these behaviors (which I guess is automatically true if autofocus is implemented using its hooks) might make sense.

> * [ ]   Any knowledge of what metadata tags are required? The metadata requirements are a huge mess as there are many hidden tags required in different parts of the software and as far as I know the minimal set is not documented anywhere. I remember some of the requirements, and the rest I've been slowly figuring out empirically by copying the clojure engine's output (which is hard, because there don't seem to be any exceptions when they're missing). Any additional knowledge would help this process

Yes.

Okay, I'm kidding. But the problem is that nothing is truly known other than that the current code (more or less) works. It would be great to come up with a specification, and we really should, but the only way to do this is to patiently study where each tag is generated and consumed (note that this differs from empirical determination, which fails to find all tags that are conditionally present).

I started doing this when I created the `PropertyKey` enum class. My vision at the time was to put all knowledge about each known tag into this class in a programmatically accessible way: for example, so that you could ask for the set of required and optional tags for summary metadata. This was to include dealing with variant spellings, too (see `INTERVAL_MS`, sigh). But unfortunately I did not finish that work. Happy to collaborate on restarting this work (or some alternative), but I do have to disappoint you if you were hoping for a ready-made list of required keys.

> * [ ]   any objections to me deleting the [Clojure stuff](https://micro-manager.org/Clojure) on the website now? And maybe cleaning up [this page ](https://micro-manager.org/Multi-Dimensional_Acquisition_Programming) on MDA programming which appears to be outdated?

None whatsoever!

**Comment by henrypinkard** [comment]
Thanks! I think this gives me enough to move forward

> Yes.
> 
> Okay, I'm kidding. But the problem is that nothing is truly known other than that the current code (more or less) works. It would be great to come up with a specification, and we really should, but the only way to do this is to patiently study where each tag is generated and consumed 

😂 You had my hopes up there for a moment

**Comment by marktsuchida** [comment]
> You had my hopes up there for a moment

Well the literal answer to each sentence in your question was "yes". Especially the second sentence....

**Comment by nicost** [comment]
B.t.w., I am unable to compile or test your branch, presumably since some dependencies are updates too.  Is it possible to update the buildscripts so that I can use the correct dependencies, or do I have to set up a super project that includes the code to all?

**Comment by nicost** [comment]
I'd first like to test if the existing Acquisition engine still works as expected.  Are the changed dependencies backwards compatible?  In that case, it would be fine to add those to the main branch.  I would not want to merge this branch until we have ensured it does not break things (and until we cleaned up the code).  

B.t.w., PycroManager 0.28 does not download for me.  Wait a bit?

**Comment by henrypinkard** [comment]
That makes sense.

No, its not backwards compatible.

PM 0.28 didn't build because I pushed it too soon after an updated AcqEngJ (this system is quite finicky). But I just re ran it so maybe in a couple mins: https://github.com/micro-manager/pycro-manager/actions/runs/3430886056

**Comment by henrypinkard** [comment]
Should be released now

**Comment by marktsuchida** [comment]
I'm not understanding why this is ready to be merged if one must fear for objectives crashing -- unless prominently marked as experimental and dangerous.

I'd like to review this in detail so I understand the consequences. Can I have a couple days before we go forward?

**Comment by henrypinkard** [comment]
fine by me

**Comment by henrypinkard** [comment]
> unless prominently marked as experimental and dangerous.

It is now prominently marked as experimental and DANGEROUS :)

Ready for merge @marktsuchida ? This shouldn't have any effects on normal operation of acquisitions unless the checkbox is clicked. 

In part I would like to merge this sooner rather than later because having multiple branches where acqEngJ  is potentially changing makes me much more prone to mistakes (like https://github.com/micro-manager/pycro-manager/issues/449). I definitely can (and will) improve workflows and tests in the future to make this less likely, but in the meantime this would be very helpful

**Comment by henrypinkard** [comment]
Wait scratch that https://github.com/micro-manager/pycro-manager/issues/449 is unrelated

**Comment by marktsuchida** [comment]
Yes, I'm all for branches with short lifetime, and one way to achieve that is to have an in-development feature in the main branch but disabled by default. With the clear marking now added, I think there is no reason not to merge.

Ready to merge once linting errors are fixed.

**Comment by nicost** [comment]
Happy to help with the linting @Henry, but could you try https://github.com/micro-manager/micro-manager/pull/1548 first?  B.t.w., anything against merging #1548?

**Comment by henrypinkard** [comment]
Yes, working on it...

**Comment by nicost** [comment]
I linted this code and pushed it to nicost/acq_eng_studio_ns.  How do I push this into Henry's branch?

**Comment by marktsuchida** [comment]
@nicost Since the branch for this PR is on @henrypinkard's fork, you need to
- add a "remote" for @henrypinkard's fork (`git remote add henrypinkard https://github.com/henrypinkard/micro-manager.git`),
- fetch it (`git fetch henrypinkard`),
- then checkout his branch (`git checkout acq_eng_studio`).
Then you can commit to that branch and push.

(The last command would need to be `git checkout acq_eng_studio henrypinkard/acq_eng_studio` if `acq_eng_studio` were not unique.)

**Comment by nicost** [comment]
So weird that I can push to Henry's branch.  I did and it seems to have gone in and the Lint task now passes.  Please make sure it compiles before merging, I did not manage to get all dependencies correct.

**Comment by nicost** [comment]
Nice!  The CI showed a problem compiling, and I just fixed it;)

**Comment by marktsuchida** [comment]
> > So weird that I can push to Henry's branch.
> 
> Yeah strange...

When you create a pull request from a fork, there is a checkbox "Allow edits and access to secrets by maintainers". It is checked by default.

**Pull request merged**
