### PR TITLE
Add support for multi-ROI mode

### PR DESCRIPTION
**Pull request by ChrisWeisiger**
This adds functions to Camera devices, the Core, and the Java layer to support the ability to set multiple simultaneous ROIs.

Note that µManager will use the bounding box of each selection component to define the list of ROIs -- thus, if you have a non-rectangular selection like an ellipse or polygon as part of your multi-selection, µManager will use its bounding box instead of erroring out. This is due to a limitation of ImageJ which makes extracting the original true ROI difficult. See this thread:

http://forum.imagej.net/t/extract-sub-rois-from-composite-roi/1645

### CODE REVIEW

**Comment by ChrisWeisiger** [comment]
I'm unable to load config files with multiple cameras with this change. I get an error about trying to change the camera while a sequence acquisition is running. I don't know why that's happening. 

Here's a config file that repros the problem:

    Property,Core,Initialize,0
▫▫▫▫
    Device,Camera,DemoCamera,DCam
    Device,Multi Camera,Utilities,Multi Camera
    Device,Camera2,DemoCamera,DCam
▫▫▫▫
    Property,Core,Initialize,1
▫▫▫▫
    Property,Core,Camera,Multi Camera
    
    ConfigGroup,CoreCamera,Camera2,Core,Camera,Camera2
    ConfigGroup,CoreCamera,Camera,Core,Camera,Camera
    ConfigGroup,CoreCamera,Multi Camera,Core,Camera,Multi Camera
    
    ConfigGroup,System,Startup,Camera,PixelType,8bit
    ConfigGroup,System,Startup,Camera,ScanMode,1
    ConfigGroup,System,Startup,Camera,RotateImages,1
    ConfigGroup,System,Startup,Camera2,PixelType,8bit
    ConfigGroup,System,Startup,Camera2,RotateImages,1
    ConfigGroup,System,Startup,Multi Camera,Physical Camera 1,Camera
    ConfigGroup,System,Startup,Multi Camera,Physical Camera 2,Camera2
    ConfigGroup,System,Startup,Core,Camera,Multi Camera

And here's the corresponding log:

    2016-05-20T08:47:39.458349 tid0x12620b000 [dbg,Core] Will set Core property: Initialize = 0
    2016-05-20T08:47:39.458363 tid0x12620b000 [dbg,Core] Will unload all devices
    2016-05-20T08:47:39.458365 tid0x12620b000 [IFO,Core] Did unload all devices
    2016-05-20T08:47:39.458387 tid0x12620b000 [dbg,App] Notification for Device: Core Property: Initialize changed to value: 0
    2016-05-20T08:47:39.458537 tid0x12620b000 [dbg,Core] Did set Core property: Initialize = 0
    2016-05-20T08:47:39.458552 tid0x12620b000 [dbg,Core] Will load device DCam from DemoCamera
    2016-05-20T08:47:39.458614 tid0x12620b000 [IFO,Core] Did load device DCam from DemoCamera; label = Camera
    2016-05-20T08:47:39.458626 tid0x12620b000 [dbg,Core] Will load device Multi Camera from Utilities
    2016-05-20T08:47:39.458677 tid0x12620b000 [IFO,Core] Did load device Multi Camera from Utilities; label = Multi Camera
    2016-05-20T08:47:39.458688 tid0x12620b000 [dbg,Core] Will load device DCam from DemoCamera
    2016-05-20T08:47:39.458730 tid0x12620b000 [IFO,Core] Did load device DCam from DemoCamera; label = Camera2
    2016-05-20T08:47:39.458744 tid0x12620b000 [dbg,Core] Will set Core property: Initialize = 1
    2016-05-20T08:47:39.458752 tid0x12620b000 [IFO,Core] Will initialize 3 devices
    2016-05-20T08:47:39.458756 tid0x12620b000 [IFO,Core] Will initialize device Camera
    2016-05-20T08:47:39.458761 tid0x12620b000 [IFO,dev:Camera] Parent Hub not defined.
    2016-05-20T08:47:39.458772 tid0x12620b000 [dbg,dev:Camera] Setting Allowed Binning settings
    2016-05-20T08:47:39.458877 tid0x12620b000 [dbg,dev:Camera] Reading property ScanMode
    2016-05-20T08:47:39.458905 tid0x12620b000 [IFO,Core] Did initialize device Camera
    2016-05-20T08:47:39.458911 tid0x12620b000 [IFO,Core] Default camera set to Camera
    2016-05-20T08:47:39.458915 tid0x12620b000 [IFO,Core] Will initialize device Multi Camera
    2016-05-20T08:47:39.458928 tid0x12620b000 [IFO,dev:Multi Camera] 0x7f9c7b01d1f0 0x7f9c7b0951b0
    2016-05-20T08:47:39.458933 tid0x12620b000 [IFO,dev:Multi Camera] 0x7f9c7b01d1f0 0x0
    2016-05-20T08:47:39.458937 tid0x12620b000 [IFO,dev:Multi Camera] 0x7f9c7b01d1f0 0x7f9c7b0996c0
    2016-05-20T08:47:39.458958 tid0x12620b000 [IFO,Core] Did initialize device Multi Camera
    2016-05-20T08:47:39.458962 tid0x12620b000 [IFO,Core] Default camera set to Multi Camera
    2016-05-20T08:47:39.458965 tid0x12620b000 [IFO,Core] Will initialize device Camera2
    2016-05-20T08:47:39.458969 tid0x12620b000 [IFO,dev:Camera2] Parent Hub not defined.
    2016-05-20T08:47:39.458979 tid0x12620b000 [dbg,dev:Camera2] Setting Allowed Binning settings
    2016-05-20T08:47:39.459086 tid0x12620b000 [dbg,dev:Camera2] Reading property ScanMode
    2016-05-20T08:47:39.459107 tid0x12620b000 [IFO,Core] Did initialize device Camera2
    2016-05-20T08:47:39.459110 tid0x12620b000 [IFO,Core] Default camera set to Camera2
    2016-05-20T08:47:39.459114 tid0x12620b000 [IFO,Core] Finished initializing 3 devices
    2016-05-20T08:47:39.459155 tid0x12620b000 [dbg,App] Notification for Device: Core Property: Initialize changed to value: 1
    2016-05-20T08:47:39.459255 tid0x12620b000 [dbg,Core] Did set Core property: Initialize = 1
    2016-05-20T08:47:39.459265 tid0x12620b000 [dbg,Core] Will set Core property: Camera = Multi Camera
    2016-05-20T08:47:39.459272 tid0x12620b000 [IFO,Core] Default camera set to Multi Camera
    2016-05-20T08:47:39.459287 tid0x12620b000 [dbg,App] Notification for Device: Core Property: Camera changed to value: Multi Camera
    2016-05-20T08:47:39.459339 tid0x12620b000 [dbg,Core] Did set Core property: Camera = Multi Camera
    2016-05-20T08:47:39.459356 tid0x12620b000 [dbg,Core] Config group CoreCamera: preset Camera2: added setting Core-Camera = Camera2
    2016-05-20T08:47:39.459365 tid0x12620b000 [dbg,Core] Config group CoreCamera: preset Camera: added setting Core-Camera = Camera
    2016-05-20T08:47:39.459375 tid0x12620b000 [dbg,Core] Config group CoreCamera: preset Multi Camera: added setting Core-Camera = Multi Camera
    2016-05-20T08:47:39.459385 tid0x12620b000 [dbg,Core] Config group System: preset Startup: added setting Camera-PixelType = 8bit
    2016-05-20T08:47:39.459393 tid0x12620b000 [dbg,Core] Config group System: preset Startup: added setting Camera-ScanMode = 1
    2016-05-20T08:47:39.459401 tid0x12620b000 [dbg,Core] Config group System: preset Startup: added setting Camera-RotateImages = 1
    2016-05-20T08:47:39.459409 tid0x12620b000 [dbg,Core] Config group System: preset Startup: added setting Camera2-PixelType = 8bit
    2016-05-20T08:47:39.459417 tid0x12620b000 [dbg,Core] Config group System: preset Startup: added setting Camera2-RotateImages = 1
    2016-05-20T08:47:39.459426 tid0x12620b000 [dbg,Core] Config group System: preset Startup: added setting Multi Camera-Physical Camera 1 = Camera
    2016-05-20T08:47:39.459434 tid0x12620b000 [dbg,Core] Config group System: preset Startup: added setting Multi Camera-Physical Camera 2 = Camera2
    2016-05-20T08:47:39.459441 tid0x12620b000 [dbg,Core] Config group System: preset Startup: added setting Core-Camera = Multi Camera
    2016-05-20T08:47:39.459457 tid0x12620b000 [dbg,Core] Waiting for device Camera...
    2016-05-20T08:47:39.459460 tid0x12620b000 [dbg,Core] Finished waiting for device Camera
    2016-05-20T08:47:39.459462 tid0x12620b000 [dbg,Core] Waiting for device Multi Camera...
    2016-05-20T08:47:39.459464 tid0x12620b000 [dbg,Core] Finished waiting for device Multi Camera
    2016-05-20T08:47:39.459466 tid0x12620b000 [dbg,Core] Waiting for device Camera2...
    2016-05-20T08:47:39.459468 tid0x12620b000 [dbg,Core] Finished waiting for device Camera2
    2016-05-20T08:47:39.459469 tid0x12620b000 [dbg,Core] Will update system state cache
    2016-05-20T08:47:39.459568 tid0x12620b000 [dbg,dev:Camera] Reading property ScanMode
    2016-05-20T08:47:39.459909 tid0x12620b000 [dbg,dev:Camera2] Reading property ScanMode
    2016-05-20T08:47:39.460061 tid0x12620b000 [IFO,Core] Did update system state cache
    2016-05-20T08:47:39.460096 tid0x12620b000 [dbg,Core] Config group System: will apply preset Startup
    2016-05-20T08:47:39.460101 tid0x12620b000 [dbg,Core:dev:Camera] Will set property "PixelType" to "8bit"
    2016-05-20T08:47:39.460110 tid0x12620b000 [dbg,Core:dev:Camera] Did set property "PixelType" to "8bit"
    2016-05-20T08:47:39.460113 tid0x12620b000 [dbg,Core:dev:Camera] Will set property "ScanMode" to "1"
    2016-05-20T08:47:39.460119 tid0x12620b000 [dbg,dev:Camera] Setting Allowed Binning settings
    2016-05-20T08:47:39.460171 tid0x12620b000 [dbg,App] Notification from MMCore ignored since the system is still loading
    2016-05-20T08:47:39.460191 tid0x12620b000 [dbg,Core:dev:Camera] Did set property "ScanMode" to "1"
    2016-05-20T08:47:39.460194 tid0x12620b000 [dbg,Core:dev:Camera] Will set property "RotateImages" to "1"
    2016-05-20T08:47:39.460198 tid0x12620b000 [dbg,Core:dev:Camera] Did set property "RotateImages" to "1"
    2016-05-20T08:47:39.460201 tid0x12620b000 [dbg,Core:dev:Camera2] Will set property "PixelType" to "8bit"
    2016-05-20T08:47:39.460204 tid0x12620b000 [dbg,Core:dev:Camera2] Did set property "PixelType" to "8bit"
    2016-05-20T08:47:39.460207 tid0x12620b000 [dbg,Core:dev:Camera2] Will set property "RotateImages" to "1"
    2016-05-20T08:47:39.460210 tid0x12620b000 [dbg,Core:dev:Camera2] Did set property "RotateImages" to "1"
    2016-05-20T08:47:39.460213 tid0x12620b000 [dbg,Core:dev:Multi Camera] Will set property "Physical Camera 1" to "Camera"
    2016-05-20T08:47:39.460363 tid0x12620b000 [dbg,Core:dev:Multi Camera] Did set property "Physical Camera 1" to "Camera"
    2016-05-20T08:47:39.460373 tid0x12620b000 [dbg,Core:dev:Multi Camera] Will set property "Physical Camera 2" to "Camera2"
    2016-05-20T08:47:39.460414 tid0x12620b000 [dbg,Core:dev:Multi Camera] Did set property "Physical Camera 2" to "Camera2"
    2016-05-20T08:47:39.460518 tid0x12620b000 [IFO,Core] Unloading all devices after failure to load system configuration
    2016-05-20T08:47:39.460532 tid0x12620b000 [dbg,Core] Will unload all devices
    2016-05-20T08:47:39.471353 tid0x17d66a000 [ERR,Core] Attempt to log message from unregistered device: Sequence thread exiting
    2016-05-20T08:47:39.471367 tid0x17d66a000 [ERR,Core] AcqFinished() called from unregistered device
    2016-05-20T08:47:39.471513 tid0x17d6ed000 [ERR,Core] Attempt to log message from unregistered device: SeqAcquisition interrupted by the user
    2016-05-20T08:47:39.471528 tid0x17d6ed000 [ERR,Core] Attempt to log message from unregistered device: Sequence thread exiting
    2016-05-20T08:47:39.471542 tid0x17d6ed000 [ERR,Core] AcqFinished() called from unregistered device
    2016-05-20T08:47:39.471819 tid0x12620b000 [IFO,Core] Did unload all devices
    2016-05-20T08:47:39.471837 tid0x12620b000 [IFO,Core] Now rethrowing original error from system configuration loading
    2016-05-20T08:47:39.479564 tid0x12620b000 [IFO,App] Failed to load hardware configuation
                                              [       ] java.lang.Exception: Cannot switch camera device while sequence acquisition is running in Thread[AWT-EventQueue-0,6,main]
                                              [       ]   at mmcorej.MMCoreJJNI.CMMCore_loadSystemConfiguration(Native Method)
                                              [       ]   at mmcorej.CMMCore.loadSystemConfiguration(CMMCore.java:361)
                                              [       ]   at org.micromanager.internal.MMStudio.loadSystemConfiguration(MMStudio.java:1185)
                                              [       ]   at org.micromanager.internal.MMStudio.setSysConfigFile(MMStudio.java:697)
                                              [       ]   at org.micromanager.internal.menus.ConfigMenu.loadConfiguration(ConfigMenu.java:119)
                                              [       ]   at org.micromanager.internal.menus.ConfigMenu.access$200(ConfigMenu.java:35)
                                              [       ]   at org.micromanager.internal.menus.ConfigMenu$3.run(ConfigMenu.java:76)
                                              [       ]   at org.micromanager.internal.utils.GUIUtils$2.actionPerformed(GUIUtils.java:344)
                                              [       ]   at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
                                              [       ]   at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
                                              [       ]   at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
                                              [       ]   at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
                                              [       ]   at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
                                              [       ]   at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
                                              [       ]   at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
                                              [       ]   at java.awt.MenuItem.processEvent(MenuItem.java:628)
                                              [       ]   at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
                                              [       ]   at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
                                              [       ]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
                                              [       ]   at java.awt.EventQueue.access$500(EventQueue.java:97)
                                              [       ]   at java.awt.EventQueue$3.run(EventQueue.java:709)
                                              [       ]   at java.awt.EventQueue$3.run(EventQueue.java:703)
                                              [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                              [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
                                              [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
                                              [       ]   at java.awt.EventQueue$4.run(EventQueue.java:731)
                                              [       ]   at java.awt.EventQueue$4.run(EventQueue.java:729)
                                              [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                              [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
                                              [       ]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
                                              [       ]   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
                                              [       ]   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                                              [       ]   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
                                              [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                                              [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
                                              [       ]   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ChrisWeisiger** [comment]
Root cause appears to be that, during loading of the system startup config, we try to set the pixel type for a DemoCamera, but it thinks that it's running a sequence acquisition, and refuses. Stack trace from Visual Studio:

    mmgr_dal_DemoCamera.dll!CDemoCamera::IsCapturing()  Line 1143    C++
    mmgr_dal_DemoCamera.dll!CDemoCamera::OnPixelType(MM::PropertyBase * pProp, MM::ActionType eAct)  Line 1334 + 0x19 bytes    C++
    mmgr_dal_DemoCamera.dll!MM::Action<CDemoCamera>::Execute(MM::PropertyBase * pProp, MM::ActionType eAct)  Line 99 + 0x43 bytes    C++
    mmgr_dal_DemoCamera.dll!MM::Property::Apply()  Line 169 + 0x23 bytes    C++
    mmgr_dal_DemoCamera.dll!MM::PropertyCollection::Set(const char * pszPropName, const char * pszValue)  Line 287 + 0xa bytes    C++
    mmgr_dal_DemoCamera.dll!CDeviceBase<MM::Camera,CDemoCamera>::SetProperty(const char * name, const char * value)  Line 512 + 0x1b bytes    C++
    MMCoreJ_wrap.dll!DeviceInstance::SetProperty(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & name, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & value)  Line 165 + 0x6e bytes    C++
    MMCoreJ_wrap.dll!CMMCore::applyConfiguration(const Configuration & config)  Line 6987 + 0x8c bytes    C++
    MMCoreJ_wrap.dll!CMMCore::setConfig(const char * groupName, const char * configName)  Line 4798 + 0x12 bytes    C++
    MMCoreJ_wrap.dll!CMMCore::loadSystemConfigurationImpl(const char * fileName)  Line 6503    C++  
    MMCoreJ_wrap.dll!CMMCore::loadSystemConfiguration(const char * fileName)  Line 6262 + 0x15 bytes    C++

I'm at a loss. Any ideas?

**Comment by ChrisWeisiger** [comment]
False alarm; I needed to rebuild the Utilities device adapter code. This is what I get for trying to get by building only the device adapters I (think I) need.

**Comment by ChrisWeisiger** [comment]
The above was only possible because I forgot to bump the device API version number; that needs to be fixed.

**Comment by marktsuchida** [comment]
Replaced by #284 and #286.

**Pull request closed without merging**
