### PR TITLE
updated magellan and library versions

### PR DESCRIPTION
**Pull request by henrypinkard**

### CODE REVIEW

**Comment by nicost** [comment]
@henrypinkard: Can you precede your commit messages with the area it touches, for instance: 

Build: updated  AcqEngJ version
Magellan: refactored use of AcqEngJ datasink

That will make it so much easier to read through commit messages in the future.  Also, you can add multiple lines (for instance to write the new version of the library that you are using now)

**Comment by henrypinkard** [comment]
Will do!

**Comment by nicost** [comment]
running `ant - f buildscripts/fetchdeps.xml` now yields:

org.micro-manager.pycro-manager#PycroManagerJava;0.6.2: not found

Was Pycromanager 0.6.2 not uploaded yet?

**Comment by henrypinkard** [comment]
Guess I forgot. It should be up now

**Comment by nicost** [comment]
@henrypinkard also wondering if it is better to use Snapshot builds.  Those are always checked to see if there is a newer version around, and do not need adding new versions continuously

**Comment by henrypinkard** [comment]
Maybe so if its not too hard to set up, though I _think_ I'm done for now

**Pull request merged**
