### PR TITLE
Add SouthPort device microz adapter

### PR DESCRIPTION
**Pull request by maobaoqi**
Product MicroZ hardware deivce adapter

### CODE REVIEW

**Comment by marktsuchida** [comment]
Apologies for the delay, I'll look at this soon.

**Comment by maobaoqi** [comment]
> Apologies for the delay, I'll look at this soon.

thank you^_^

**Comment by maobaoqi** [comment]
> Apologies for the delay, I'll look at this soon.

Hi, Mark
Please merge the PR if you have time, thanks!^_^

**Comment by nicost** [comment]
Sorry for the delay!  

I just added your code to the subversion repository (still our main repo for the C++ code).  It build perfectly on my Windows machine, and looks very clean.  It should be in tomorrows nightly builds of 1.4 and 2.0. Thanks!  

If you want to make changes in the future, it would be great if you can send me a private email, so that I can make you an account on the svn repo and you can commit there directly.

Also, it would be wonderful if you can make a page describing the device adapter and how to use it on the Micro-Manager website (https://micro-manager.org). Send me an email after you request an account so I can approve it.

**Pull request closed without merging**
