### PR TITLE
Update Ivy artifact definitions for the jogl and gluegen dependencies…

### PR DESCRIPTION
**Pull request by fabio-echegaray**
…; they are now fetched from Maven central repository.

### CODE REVIEW

**Comment by marktsuchida** [comment]
This is nice!
I'll give this a test to make sure everything is right in the produced installers (for different platforms).

One thing that should be updated is the source of DLLs copied to the stage directory by the Ant script `plugins/MMClearVolumePlugin/build.xml`. The DLLs should now be extracted from the fetched Jars. No need to do that as part of this PR (unless you want to), just making a note to myself.

**Comment by marktsuchida** [comment]
In the macOS build's `plugins/Micro-Manager` I get these differences:
```
--- before	2022-02-02 11:12:24.000000000 -0600
+++ after	2022-02-02 11:11:47.000000000 -0600
@@ -45,7 +45,6 @@
 formats-gpl-5.5.3.jar
 GaussianLibrary.jar
 georegression-0.22.jar
-gluegen-2.3.2.jar
 gluegen-rt-2.3.2-natives-android-aarch64.jar
 gluegen-rt-2.3.2-natives-android-armv6.jar
 gluegen-rt-2.3.2-natives-linux-amd64.jar
@@ -57,12 +56,10 @@
 gluegen-rt-2.3.2-natives-solaris-i586.jar
 gluegen-rt-2.3.2-natives-windows-amd64.jar
 gluegen-rt-2.3.2-natives-windows-i586.jar
-gluegen-rt-local-2.3.2.jar
+gluegen-rt-2.3.2.jar
+gluegen-rt-main-2.3.2-javadoc.jar
+gluegen-rt-main-2.3.2-sources.jar
 gluegen-rt-main-2.3.2.jar
-gluegen-rt-main-local-2.3.2.jar
-gluegen-rt-natives-macosx-universal-2.3.2.jar
-gluegen-rt-natives-windows-amd64-2.3.2.jar
-gluegen-rt-natives-windows-i586-2.3.2.jar
 gson-2.2.4.jar
 guava-17.0.jar
 hamcrest-core-1.3.jar
@@ -100,12 +97,10 @@
 jogl-all-2.3.2-natives-solaris-i586.jar
 jogl-all-2.3.2-natives-windows-amd64.jar
 jogl-all-2.3.2-natives-windows-i586.jar
-jogl-all-local-2.3.2.jar
+jogl-all-2.3.2.jar
+jogl-all-main-2.3.2-javadoc.jar
+jogl-all-main-2.3.2-sources.jar
 jogl-all-main-2.3.2.jar
-jogl-all-main-local-2.3.2.jar
-jogl-all-natives-macosx-universal-2.3.2.jar
-jogl-all-natives-windows-amd64-2.3.2.jar
-jogl-all-natives-windows-i586-2.3.2.jar
 jsr250-api-1.0.jar
 jsr305-3.0.2.jar
 junit-4.12.jar
```

(`before` is the nightly build of 20220201)

- I'd say we don't need the `sources` and `javadoc` Jars
- As far as I can tell, the removed Jars are all redundant or replaced by a non-`local` copy, except for `gluegen-2.3.2.jar`
    - This seems okay, if gluegen (being a code generator) is not needed either for our build (confirmed) or at runtime (need to confirm -- @nicost do you know?)

I'll take further look when I have a chance (also on Windows).

**Comment by nicost** [comment]
I have no recollection about gluegen.  I just removed it from a Micro-Manager installation, and the ClearVolume plugin remains fully functional, suggesting that it can be safely removed.

**Comment by marktsuchida** [comment]
@nicost Thanks!

**Comment by fabio-echegaray** [comment]
Hi @marktsuchida! I am happy to update the PR to remove the DLLs you mention, and could also try compiling the code on Windows and Mac as well; I'll let you know how I get on with that. With that being said, it is not entirely clear to me what are the key tests that I should try though, is there any information regarding that in the docs, like a document for tests or a battery of unit tests? Cheers!

**Comment by marktsuchida** [comment]
@fabio-echegaray I think making sure that the ClearVolume plugin (3D view) works correctly is the only real test here.

I'm pretty sure this is good to go after removing the sources and javadoc jars; I just want to do one last check using a full build on Windows -- I'll probably get to that tomorrow-ish.

**Comment by marktsuchida** [comment]
In a full Windows build (the nightly build script), the JARs look good, but the DLLs are missing (see diff of file listing below).

**But** when I test the 3D viewer with the DLLs missing, it just worked, and furthermore, I can see the DLLs being extracted into my temporary directory (`%USERPROFILE%\AppData\Local\Temp\jogamp_0000\`).

So at least with the Jars fetched from Maven, it appears that we no longer need to ship these DLLs.

(I think we were packaging the DLLs only because the auto-extraction mechanism was not functional or not reliable in the past.)

I'm going to push a commit to remove the DLL copying, then merge.

```
--- before-all  2022-02-03 14:52:11.622310100 -0600
+++ after-all   2022-02-03 14:55:23.112043500 -0600
@@ -31,13 +31,10 @@
 ./TIS_UDSHL10_x64.dll
 ./XCLIBW64.dll
 ./atmcd64d.dll
-./gluegen-rt.dll
 ./hidapi.dll
 ./hrfw64.dll
 ./ij.jar
 ./inpoutx64.dll
-./jogl_desktop.dll
-./jogl_mobile.dll
 ./jre
 ./jre/COPYRIGHT
 ./jre/LICENSE
@@ -588,9 +585,6 @@
 ./modbus.dll
 ./mrc564.dll
 ./mrfw64.dll
-./nativewindow_awt.dll
-./nativewindow_win32.dll
-./newt.dll
 ./obsROE_Device.dll
 ./okolib
 ./okolib.dll
@@ -662,14 +656,12 @@
 ./plugins/Micro-Manager/formats-common-5.1.1.jar
 ./plugins/Micro-Manager/formats-gpl-5.5.3.jar
 ./plugins/Micro-Manager/georegression-0.22.jar
-./plugins/Micro-Manager/gluegen-2.3.2.jar
+./plugins/Micro-Manager/gluegen-rt-2.3.2-natives-linux-i586.jar
+./plugins/Micro-Manager/gluegen-rt-2.3.2-natives-macosx-universal.jar
+./plugins/Micro-Manager/gluegen-rt-2.3.2-natives-windows-amd64.jar
 ./plugins/Micro-Manager/gluegen-rt-2.3.2-natives-windows-i586.jar
-./plugins/Micro-Manager/gluegen-rt-local-2.3.2.jar
+./plugins/Micro-Manager/gluegen-rt-2.3.2.jar
 ./plugins/Micro-Manager/gluegen-rt-main-2.3.2.jar
-./plugins/Micro-Manager/gluegen-rt-main-local-2.3.2.jar
-./plugins/Micro-Manager/gluegen-rt-natives-macosx-universal-2.3.2.jar
-./plugins/Micro-Manager/gluegen-rt-natives-windows-amd64-2.3.2.jar
-./plugins/Micro-Manager/gluegen-rt-natives-windows-i586-2.3.2.jar
 ./plugins/Micro-Manager/gson-2.2.4.jar
 ./plugins/Micro-Manager/guava-17.0.jar
 ./plugins/Micro-Manager/hamcrest-core-1.3.jar
@@ -695,13 +687,14 @@
 ./plugins/Micro-Manager/jnacl-1.0.0.jar
 ./plugins/Micro-Manager/jocl-2.0.1.jar
 ./plugins/Micro-Manager/joda-time-2.2.jar
+./plugins/Micro-Manager/jogl-all-2.3.2-natives-linux-i586.jar
+./plugins/Micro-Manager/jogl-all-2.3.2-natives-macosx-universal.jar
+./plugins/Micro-Manager/jogl-all-2.3.2-natives-windows-amd64.jar
 ./plugins/Micro-Manager/jogl-all-2.3.2-natives-windows-i586.jar
-./plugins/Micro-Manager/jogl-all-local-2.3.2.jar
+./plugins/Micro-Manager/jogl-all-2.3.2.jar
+./plugins/Micro-Manager/jogl-all-main-2.3.2-javadoc.jar
+./plugins/Micro-Manager/jogl-all-main-2.3.2-sources.jar
 ./plugins/Micro-Manager/jogl-all-main-2.3.2.jar
-./plugins/Micro-Manager/jogl-all-main-local-2.3.2.jar
-./plugins/Micro-Manager/jogl-all-natives-macosx-universal-2.3.2.jar
-./plugins/Micro-Manager/jogl-all-natives-windows-amd64-2.3.2.jar
-./plugins/Micro-Manager/jogl-all-natives-windows-i586-2.3.2.jar
 ./plugins/Micro-Manager/jsr250-api-1.0.jar
 ./plugins/Micro-Manager/jsr305-3.0.2.jar
 ./plugins/Micro-Manager/junit-4.12.jar
```

**Comment by fabio-echegaray** [comment]
Hello @marktsuchida, that is great to hear! I was trying to get the project to compile on Windows, to try what the night build did, but I am still on the learning curve. Perhaps it would be worth to simplify the dependencies overall, now that it seems the building tools have matured?

**Comment by marktsuchida** [comment]
@fabio-echegaray Yep, that is the direction we're taking. It will take a while given the complexity and many requirements on our build system.

**Pull request merged**
