### PR TITLE
ASI PLogic Control: a new plugin for the TGPLC card

### PR DESCRIPTION
**Pull request by bls337**
First commit for the ASI PLogic Control plugin, this plugin lets you program the TGPLC using a graphical user interface.

### CODE REVIEW

**Comment by marktsuchida** [comment]
@bls337 Would you mind trying the instructions in doc/pre-commit-md? (Make sure to check the setup for IntelliJ.)
(And bear with us until we introduce an autoformatter....)

Feel free to also do the following or leave for me:
- [ ] Add `ASIPLogic.jar` to `plugins/Makefile.am`

**Comment by bls337** [comment]
I tried to import the checkstyle.xml file but I got an error: "File 'checkstyle.xml' has invalid format."

I managed to import this file a couple of months ago, but I'm not sure what happened to it. I'm using the latest version of IntelliJ, CheckStyle-IDEA 5.92.0, and Windows 10 Pro.

**Comment by bls337** [comment]
I added `ASIPLogic.jar` to `plugins/Makefile.am`, I think I did things correctly, but I noticed that that there isn't an entry for `ASIRingTIRF.jar`, should there be one? I still seem to be able to access the ASIRingTIRF plugin regardless.

**Comment by marktsuchida** [comment]
Thanks @bls337 !

`Makefile.am` only affects the macOS and Linux builds, so `ASIRingTIRF.jar` is presumably missing there, too. I'll go ahead and add that in a separate PR after merging this one.

**Comment by bls337** [comment]
Thanks, that's good to know!

**Pull request merged**
