### PR TITLE
Revert "Added option to copy to the system clipboard to the export images as displayed gear menu."

### PR DESCRIPTION
**Pull request by henrypinkard**
Reverts micro-manager/micro-manager#1669

Whoops sorry I'll let @marktsuchida sign off on this

### CODE REVIEW

**Comment by nicost** [comment]
This is very confusing.  Where is the orginal PR?  Do I need to generate it again?

**Comment by nicost** [comment]
Can you undo this revert?  I have no idea how to get my PR back in, and would like to merge it now.

**Comment by nicost** [comment]
OK, Reverted the revert. Will need to check how that comes out, will be a messy history...

**Comment by henrypinkard** [comment]
Sorry!

**Pull request merged**
