### PR TITLE
Modified MultipageTiffWriter to split large stacks more intelligently.

### PR DESCRIPTION
**Pull request by dickinson-lab**
Proposed fix for #1396

### CODE REVIEW

**Comment by marktsuchida** [comment]
I like this direction a lot -- if it works safely in all cases, it's a beautiful fix!

Does this work even if the 0th element of `orderedAxes_` is neither `Coords.Z_SLICE` (=`"z"`) nor `Coords.CHANNEL`? Or if `orderedAxes_` is empty? What happens if the intended size is set but the axis order is not set? (These situations may not happen with MDA, but could happen if the axis order is set by a script, I think.)

Also, does this work with Tools > Options > Save XY Positions in separate Image Stack Files turned either on or off?

I think the idea of limiting the chucking to slices and channels makes sense, because the other axes (time and position) have the danger of being huge (not fitting in 4 GiB). But what if somebody acquires 4 channels with 50 slices that are 32 MiB each (> 6 GiB of pixels alone)? We probably need a fallback to the current behavior so that there is no chance of falling into an infinite loop of creating new files.

@nicost and @henrypinkard I would also appreciate your thoughts on this.

**Comment by dickinson-lab** [comment]
Thanks Mark, these are very good points.  For the first two, I am pretty sure it should default back to the old behavior, but I will test and make sure.  

The last point is a very good one, I will probably need to add some additional lines of code to deal with the situation where a single timepoint is >4 GB.  Should be pretty quick now that I know what to do.

**Comment by dickinson-lab** [comment]
Ok, I am pretty sure I've addressed all the questions you asked: 

> Does this work even if the 0th element of orderedAxes_ is neither Coords.Z_SLICE (="z") nor Coords.CHANNEL? Or if orderedAxes_ is empty? 

Yes, if orderedAxes_ is empty or if the first axis is neither Z nor channel, it defaults to the original behavior. 

>What happens if the intended size is set but the axis order is not set? (These situations may not happen with MDA, but could happen if the axis order is set by a script, I think.)

There seems to be a default value of orderedAxes_ (which is channel - time - z - position) that is set somewhere else in the code.  This allows the save function to work correctly even if the calling function doesn't specify axis order. 

> Also, does this work with Tools > Options > Save XY Positions in separate Image Stack Files turned either on or off?

Yes.  If "Save XY Positions in separate Image Stack Files" is unchecked, files will not necessarily be split intelligently, in the sense that parts of a single position can end up split between two different files.  I considered adding additional code to keep each position in a single file if possible, but decided against it (if a user wants this behavior, they can just check the option to save each position in its own file." 

> What if somebody acquires 4 channels with 50 slices that are 32 MiB each (> 6 GiB of pixels alone)? We probably need a fallback to the current behavior so that there is no chance of falling into an infinite loop of creating new files.

I have added this in an additional commit, so the possibility of an infinite loop is eliminated now. 

Let me know if there are any outstanding concerns or additional tests you want me to run before merging these changes.

**Comment by marktsuchida** [comment]
Sorry I haven't looked at this yet - will do soon.

**Comment by marktsuchida** [comment]
It looks like the decision to give up due to a single time point not fitting in a single file is made based solely on `frameSize`, whose calculation takes into account the number of channels and slices, but not the number of stage positions, which would be significant in the case where the time series is the outer loop of a multi-position acquisition, and "Save XY Positions in separate Image Stack Files" is disabled.

Also, the `omeMDLength` needs to be accounted for when comparing `frameSize` to `MAX_FILE_SIZE`. (Technically there is also other per-file overhead such as summary metadata, but I expect that is small enough that `extraPadding` should take care of it.)

Sorry it took so long for me to review this -- among other things that happened, I wanted to take a careful look at this because it changes how data is saved (and we don't have good automated tests in this area, making all changes rather scary).

**Comment by dickinson-lab** [comment]
> It looks like the decision to give up due to a single time point not fitting in a single file is made based solely on frameSize, whose calculation takes into account the number of channels and slices, but not the number of stage positions, which would be significant in the case where the time series is the outer loop of a multi-position acquisition, and "Save XY Positions in separate Image Stack Files" is disabled.

Yes, this was intentional.  I'm not using stage positions as a basis for splitting files, since that behavior already exists (the user can just check the "Save XY positions in separate files" option, if desired). 

The purpose of "giving up" when a single time point won't fit is to make sure that we don't fall into an infinite loop of making new files.  There's no danger of that happening when there are too many stage positions in a file, since we don't consider the number of stage positions when deciding whether to create a new file in the first place.   

I tested this using the demo configuration to acquire a dataset with 144 positions, 31 Z slices and 4 channels (8.7 GB) with "positions in separate files" unchecked.  What happens is that stage positions 1-65 end up in the first file, 66-130 in the second file, and the last 14 positions in a the third file.  Each file contains a full complement of slices and channels for the positions it contains, and can be opened individually.  In my opinion, this is the ideal behavior in this situation. 

The reason it works this way is that `filePosition_` is included in the calculation of `size` on lines 531-534 (and on lines 538-540, which are unchanged from the original code).  This ensures that the file can never overflow. 

> Also, the omeMDLength needs to be accounted for when comparing frameSize to MAX_FILE_SIZE.

Yes, good catch.  I'll push a new commit now that adds this (line 524). 

No worries about the delay, I appreciate you taking a careful look. Let me know if you don't agree with my approach to dealing with stage positions, or if you have other concerns.

**Comment by marktsuchida** [comment]
You're right, I got confused about the XY positions.
I think this is now ready!

**Comment by nicost** [comment]
Thanks so much @dickinson-lab  and @marktsuchida.  Great effort and awesome outcome!

**Comment by dickinson-lab** [comment]
Thanks Mark!  I appreciate all your comments and suggestions.  We love Micro-Manager so it feels great to be able to contribute to the project, albeit in a small way.

**Pull request merged**
