### PR TITLE
Linting plugins: MMClearVolume, Magellan, libraries: ImaegProcessing, Gaussian

### PR DESCRIPTION
**Pull request by nicost**
All but two files in the libraries-Gaussian are now error free in Checkstyle.  I am not quite sure how to add the linted directories to .pre-commit-config.yaml (and possibly elsewhere?).

### CODE REVIEW

**Comment by marktsuchida** [comment]
In `.pre-commit-config.yaml`, the (currently) last line
```
        files: '^mmstudio/src/main/java/'
```
specifies that Checkstyle is only run on files matching the regular expression `^mmstudio/src/main/java/`.

So changing it to
```
        files: '^(mmstudio/src/main/java/|libraries/Gaussian/src/main/java/)'
```
should do the job. (The `src/main/java/` part may not be needed for libraries and plugins, unlike mmstudio. Non-Java files are excluded by a separate mechanism.)

If you want to exclude particular files, it is easier to add an `exclude:` field (at the same indentation as `files:`)

Further details are in the [pre-commit docs](https://pre-commit.com/#pre-commit-configyaml---hooks). You can test (after `git add .pre-commit-config.yaml`) with `pre-commit run --all-files`.

No need to add it anywhere else.

**Comment by nicost** [comment]
Still about 1800 errors to go in plugins...  We'll get there;)

**Comment by marktsuchida** [comment]
@nicost I think this broke the build; can you take a look?

```text
 [mm-javac] /Users/mark/devel/micro-manager/plugins/ChannelCorrector/src/main/java/org/micromanager/channelcorrector/ChannelCorrectorPanel.java:232: error: cannot find symbol
 [mm-javac]       Polygon maxima = FindLocalMaxima.FindMax(siPlus, distance_, threshold_,
 [mm-javac]                                       ^
 [mm-javac]   symbol:   method FindMax(ImagePlus,int,int,FilterType)
 [mm-javac]   location: class FindLocalMaxima
```

**Comment by nicost** [comment]
Sorry about that!  Did not have that plugin in my InteliJ project.  Fixed in PR #1527.

**Comment by marktsuchida** [comment]
Thanks! I found a few more of the same but fixed.

**Pull request merged**
