### PR TITLE
QuickAccess Panels: Fixes naming bugs

### PR DESCRIPTION
**Pull request by nicost**
Addresses issue #423.  Makes sure that new Panels have unique names, and that changed names are unique.  Also removes the use of com.bulenkov.iconloader.IconLoader (which should be removed everywhere since it is trivial code), makes variables final whenever possible and add some Javadoc.

### CODE REVIEW

**Comment by ChrisWeisiger** [comment]
Have you verified that creating a new ImageIcon instead of using IconLoader correctly uses high-DPI images when they are available? That is the reason why IconLoader is used: it identifies when the icon being drawn is on a high-DPI display, and then draws the "@2x" version of the icon if available (e.g. instead of drawing foo.png, it draws foo@2x.png). Not doing this results in a very ugly GUI on high-DPI displays.

**Comment by nicost** [comment]
Ah, Sorry!  Completely forgot about that and though we were still using the old IconLoader.  Will revert those changes.

**Comment by ChrisWeisiger** [comment]
Oh, you're thinking of that thing that we replaced with `getClass().getResource(path_to_file)`, aren't you? Yeah, as far as I'm aware, that module has been completely excised from the code and isn't even in the build any more.

**Comment by nicost** [comment]
Perfect!  Sorry for my mis-understanding/poor memory.  Just reverted back the icon loading code (and I'll remember to use the same in the future).

**Comment by marktsuchida** [comment]
Merged manually as commit 4436785874f98fbcfd1ac7fa19e66efc89b3e465.

**Pull request closed without merging**
