### PR TITLE
Change Timeout to "Core-TimeoutMs"

### PR DESCRIPTION
**Pull request by impact27**
This changes allows users to change the timeout value of the camera

### CODE REVIEW

**Comment by marktsuchida** [comment]
Thanks, @impact27. Can I ask if the motivation is to be able to set longer timeouts (because you are using external trigger?), or shorter ones (why?)?

I'm wondering in part because your change would change the default from (5 * exposure + 50) sec to (5 * exposure + 5) sec, which is rather drastic when the exposure is short. This will break existing configurations where people are expecting the camera to wait at least 50 seconds for an external trigger. So we might want to think about a different way to make the timeout configurable.

**Comment by impact27** [comment]
I am trying to use a logarithmically spaced external trigger. The reason I made this change is that as there is already a setting for a timeOut, I would expect it to change all the time outs? As a user, the Core-TimeOutMs was the first think I changed when I had this problem. The alternative would be to add another setting but there is already two. (The second one being only accessible with BeanShell, but I am unsure how to access this one from the cpp file)

**Comment by impact27** [comment]
For reference: http://micro-manager.3463995.n2.nabble.com/No-way-to-change-timeout-time-td7585801.html#a7585832

**Comment by impact27** [comment]
Or the default value of Core-TimeoutMs could be changed to 50000

**Comment by marktsuchida** [comment]
If this is still needed, we need a different solution, because `Core-TimeoutMs` is for waiting for devices to exit their "busy" state (it is already too restrictive that we only have one timeout for all devices). The only way to allow control of a camera's external trigger timeout is to add a camera-specific property.

**Pull request closed without merging**
