### PR TITLE
Port of changes Jon made in 1.4 branch after port of the diSPIM code to 2.0

### PR DESCRIPTION
**Pull request by nicost**

### CODE REVIEW

**Comment by ChrisWeisiger** [comment]
Is the GenericSLM commit (18542b6) supposed to be part of this PR?

**Comment by nicost** [comment]
No it is not.  Sorry, can you easily back that one out?

On 4/11/16 8:30 AM, ChrisWeisiger wrote:
>
> Is the GenericSLM commit (18542b6 
> <https://github.com/micro-manager/micro-manager/commit/18542b6bf9aba284f06a25781a4ae2910ec8a0d1>) 
> supposed to be part of this PR?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/micro-manager/micro-manager/pull/250#issuecomment-208402381>
>

-- 
Nico Stuurman
Vale lab, UCSF/HHMI
Genentech Hall, N316, MC2200
600 - 16th Street
San Francisco, CA 94158-2517
415 707 9488
nico.stuurman@ucsf.edu

**Comment by nicost** [comment]
Alright, I managed to get that commit out of the history of this branch.

**Comment by ChrisWeisiger** [comment]
Great, thanks for sorting that out.

**Pull request merged**
