### PR TITLE
Updates new AcqEngJ API changes

### PR DESCRIPTION
**Pull request by henrypinkard**

### CODE REVIEW

**Comment by henrypinkard** [comment]
@marktsuchida do you know what this means?

```
Run # TEMPORARY HACK to accept specific expired TLS certificate
  # TEMPORARY HACK to accept specific expired TLS certificate
  mkdir -p ~/.subversion/auth/svn.ssl.server
  cp micro-manager/.github/accept-expired-valelab4-svn \
     ~/.subversion/auth/svn.ssl.server/7abd63f9a2ebe9418dc77976036ea792
  # END TEMPORARY HACK
  mkdir 3rdpartypublic
  svn co https://valelab4.ucsf.edu/svn/3rdpartypublic/classext \
         3rdpartypublic/classext
  shell: /usr/bin/bash -e {0}
svn: E170013: Unable to connect to a repository at URL 'https://valelab4.ucsf.edu/svn/3rdpartypublic/classext'
svn: E000110: Error running context: Connection timed out
Error: Process completed with exit code 1.
```

**Comment by marktsuchida** [comment]
I saw that yesterday, too. It went away after a few hours. Server being slow?
Note that the connection timeout is separate from the previous step in which a known certificate is set up.

**Comment by henrypinkard** [comment]
Gotcha. Think this one is okay to merge and bypass the test? The changes are pretty minimal and it works fine locally

**Comment by henrypinkard** [comment]
Nevermind, looks like it worked

**Pull request merged**
