### PR TITLE
RAMPS device driver update

### PR DESCRIPTION
**Pull request by nvladimus**
Hi, I tried using RAMPS device driver for stage control, but it didn't work, this issue has some history([1](http://theo.io/blog/2018/02/01/save-99-5-upgrading-a-manual-microscope-with-an-automated-stage-for-60/), [2](https://twitter.com/theosanderson/status/959101529935564800)). I cleaned up the code, compiled in Visual Studio 2015, and tested the new 64x RAMPS device driver in various modes, including Multi-D acquisition - it works fine now.
I am opening this pull request to share my code. I am not experienced in github collaboration workflow, so please be merciful if I mess something up.

### CODE REVIEW

**Comment by nicost** [comment]
Could you email me the diffs for just the RAMPS file (i.e., none of the build files, MMDevice.h, and other things you changed to make it build on your system)?  If diffs are difficult, just email me the files themselves.

**Comment by nvladimus** [comment]
How do I email diffs? I can delete all non-RAMPS files from my pull request - will it do the job?

**Comment by nicost** [comment]
Yes, that should work fine.  Thanks!

**Comment by nvladimus** [comment]
Hi, Nico,
I deleted non-RAMPS files from my pull request, I hope this will allow smooth merge. Please, let me know if I can do anything else.

**Comment by nicost** [comment]
Committed in subversion r16814.  Can you close this PR?  B.t.w., I am not sure how Mark's discussion starting July 27th ended up in here, but it does remind me that for 3 months now, code changes from 1.4 have not been propagated back into the 2.0 branches.

**Comment by nvladimus** [comment]
OK, I hope this version will work smoothly on other's systems. If not, I will be happy to do some more debugging.

**Pull request closed without merging**
