### PR TITLE
DeviceAdapter for PeCon Series 2000 devices (incubator controllers)

### PR DESCRIPTION
**Pull request by csachs**
Hello,

see attached PR for a DeviceAdapter for PeCon Series 2000 devices (e.g. temperature and CO<sub>2</sub> controllers [http://www.pecon.biz/?page_id=126]).

I've started a new DeviceAdapter, because these devices are connected via USB and come with a SDK to interface them, in contrast to the Pecon DeviceAdapter which is for different models, which use serial connections.

Included is as well the SDK, which was kindly provided to me by Dr. Oliver Merk of PeCon GmbH (he expressed permission to have these files distributed with the MM project).

Furthermore, I have to thank Dr. Merk for fruitful discussions and his help in testing with various PeCon devices.

If accepted, I can write a short Readme on the Wiki.

Just one important note: I have edited the `PeCon2000.vcxproj` with VS 2013, which seems to be newer than what MM uses to build, furthermore I used a different Win SDK because my VS installation lacked the one MM used. The `.vcxproj` should thus be rewritten with the VS/VC version you're using to build. Building is simple, the adapter just needs the lib in the corresponding (32/64) bit folder. For runtime, both the `.dll` s provided need to be present in the MM folder.

If you have any questions or would like alterations, feel free to comment.

Best regards,
Christian Sachs

### CODE REVIEW

**Comment by marktsuchida** [comment]
Thank you! Once reviewed, we will "merge" this into Micro-Manager 1.4 SVN and later forward-port to Micro-Manager 2.

**Comment by csachs** [comment]
Thanks for the response! It was tested for quite some time under MM 1.4, so I guess this should not pose any problem. If you have questions or problems occur, feel free to ask me.

**Comment by marktsuchida** [comment]
Very sorry for the long wait.
I'll fix the `.vcxproj` file for VS2010, no problem.

The only thing I see is that `DetectDevice()` is implemented with nonstandard semantics (`DetectDevice()` should only be implemented for serial-based devices). Presumably the function can be removed (and its uses replaced with a call to `PdlEnumReset()`)?

**Comment by csachs** [comment]
Hello, thanks for the feedback.
I've removed the `DetectDevice()` function as you've requested. I was not aware that it only should be implemented in serial hubs. I don't remember which hub-device I studied as template, but https://micro-manager.org/wiki/Building_Micro-Manager_Device_Adapters made it sound like _all_ hub devices should implement `DetectDevice()`

> A well-behaved hub device should perform the following functions:
> • Auto-detection of the communication port (if any), by implementing MM::Device::DetectDevice() virtual method

Feel free to remark any further problems with the code.
Best regards, Christian

**Comment by ChrisWeisiger** [comment]
Hi Christian,

Thanks for pointing out the flaw in our wiki documentation. I've gone ahead
and fixed that up -- the reference to DetectDevice is removed, and there's
some clarification that certain of the advice is only relevant for devices
using serial ports. Hopefully the next contributor will have an easier time
of things!

-Chris

**Comment by csachs** [comment]
Hi Mark,
I don't mean to nag, but did you get my e-mails? I replied with my work e-mail.
Dr. Merk told me he was not contacted either, so far.
As the Device Adapter is already included in the nightly builds, I feel there's just very little left to do to have this adapter working and available to the general public.

Thanks, best regards,
Christian
PS: Great to see your new server in action, download speeds for nightlies are much better now!

**Comment by marktsuchida** [comment]
@csachs Apologies for the delay - I did belatedly contact Dr Merk last week, so hopefully we'll be able to take care of this shortly.

**Comment by marktsuchida** [comment]
Done in 1.4 SVN; will shortly merge into mm2.

**Pull request closed without merging**
