### PR TITLE
Projector plugin changes to make it usable with new plugin loading policies.

### PR DESCRIPTION
**Pull request by nicost**
Projector plugin: Added accessor function so that scripts and plugins can get hold of the Projector plugin
logic and use it.  Necessitated by changes in the plugin loading policies.

### CODE REVIEW

**Comment by marktsuchida** [comment]
1. Can we please not have a method named `getControlForm()` whose behavior is to _show_ the form? (Maybe name it `showControlForm()` instead?)

2. Please see my comment on #324. Do you think we could do a compromise: make the added method `private`? BeanShell scripts will still be able to call it (after calling `setAccessibility(true);`), and that way we make it explicit that it's not a stable API.

**Comment by nicost** [comment]
Guys, I think this is a very clear example of programming ideals getting 
in the way of work done.

Yes, I have been using the Projector plugin from other code for more 
than a year now, and needs access to it.  To "improve" things this 
access has been taken away and I have no way of getting my work done 
other than trying to fix the problem.  I have no desire to create a 
wonderful super-well designed programming environment, I want to get my 
work done.

If that means switching all our systems back to 1.4, so be it. If you 
want me to work on 2.0, please do let me focus on my work rather than 
creating obstructions.  So, please modify the Projector plugin so that 
it can be accessed programmatically from other scripts and plugins, and 
raise awareness that this is going to be desirable for many other 
plugins as well.


> 1.
>
>     Can we please not have a method named |getControlForm()| whose
>     behavior is to /show/ the form? (Maybe name it |showControlForm()|
>     instead?)
>

No, the goal of that function is to return the singleton instance of the 
form.  If there is no instance yet, it will be shown.  Hence, that 
function returns the controlForm and 'getControlForm" is the appropriate 
name.

> 1.
>
>     Please see my comment on #324
>     <https://github.com/micro-manager/micro-manager/issues/324>. Do
>     you think we could do a compromise: make the added method
>     |private|? BeanShell scripts will still be able to call it (after
>     calling |setAccessibility(true);|), and that way we make it
>     explicit that it's not a stable API.
>

No, since my micro-nuclei plugin code will need the same access. There 
are plenty of examples in the plugins of code accessing non-API parts of 
MM (search for "internal" imports).  IMHO this is fine, as long as the 
plugin writer is aware that this can break things at any point in time.  
Not allowing that kind of access (as was now done for all the plugins) 
will drastically increase the burden on the plugin writers, hence you 
are dramatically reducing contributions from the community, which imho 
is a very bad thing.

**Comment by marktsuchida** [comment]
Discouraging access to internal code is not "programming ideals getting in the way of work done", because code that does that will quickly become unmaintainable, vastly increasing the total amount of work in the long term, only for short-term gain. The fact that your 1-year-old code stopped working is nothing but proof that, once we expose internals, people will complain when we take them away.

However, I'm all for having ways to access internals for experimental/prototyping purposes, as long as that stance is made clear. Chris is now working on creating a separate "library" JAR for Projector. All classes in it will be in an "internal" package, for now, but they will be on the shared classpath (so will be accessible from Java as well as BeanShell).

**Comment by marktsuchida** [comment]
Issue addressed by #330.

**Pull request closed without merging**
