### PR TITLE
SmarAct HCU device adapter

### PR DESCRIPTION
**Pull request by jdeschamps**
Hi,

This is my first attempt to submit a device adapter to MM, I hope I am doing everything right!  I have been using this device adapter on our microscopes with MM 1.4.17 to 1.4.22. 

Best,
Joran

edit: More details: this device adapter allows Micromanager to control any SCU positionner controller from SmarAct (HCU-3D or CU-3D, whether they have 1, 2 or 3 channels). The users need to ask the company for a special firmware to upload on the controller so that RS232 communication can be established. The device adapter can create two types of device: XY stage and Z stage. Implemented function, besides moving the stage, concern mainly the speed and the direction of the positionners. Has been tested independently by different people/microscope already.

### CODE REVIEW

**Comment by nicost** [comment]
I added your code to the 1.4 repository.  It should be in tonight's build.  Can you add a page with the information you provided above to the Micro-Manager website (https://micro-manager.org/wiki/Device%20Support)?  If you do not have an account, simply request on at https://micro-manager.org/wiki/Special:RequestAccount

**Comment by nicost** [comment]
Can you please add documentation to the Micro-Manager website?  Your adapter code is not very useful to others without explanation.

**Comment by jdeschamps** [comment]
Sorry writing my PhD right now. Will do that during next week!

**Comment by jdeschamps** [comment]
First version done!

**Comment by nicost** [comment]
Thanks!  Closing this now.

**Pull request closed without merging**
