### PR TITLE
Update ClearVolume dependency which is now in Maven

### PR DESCRIPTION
**Pull request by fabio-echegaray**
Hello,

This PR has the following changes:

1. ClearVolume can be pulled from Maven entirely now, so I changed the relevant lines in ivy.xml.
2. The IconLoader project is not on Maven, but it has a GitHub repository at https://github.com/bulenkov/iconloader. This PR fetches the content of the GitHub repo and copies the jar from there; for this, it uses JGit (https://www.eclipse.org/jgit/).
3. The previous changes triggered some errors at compilation. Attending this, I added the Apache Commons dependencies which are required for the compilation of mmstudio (at least under Linux).

Is fetching code from GitHub something that is discouraged? If this is not welcomed, I can update the PR, let me know. Finally, I haven't tried compiling under Windows or MacOS.

### CODE REVIEW

**Comment by marktsuchida** [comment]
It would be wonderful if you could put the different changes into separate PRs, or at least separate commits :)

- I guess this happened in parallel to my cleanup #1395, which already removed the old BinTray repos for ClearVolume. Versions did not need to change there; the versions we use are available from the image.net repo.

- There is already a line for `commons-lang3` 3.5 in `ivy.xml`. It is indeed a bug that mmstudio imports `org.apache.commons.lang`, so that code change is great. (`commons-lang` gets pulled as a transitive dependency, probably for one of the other things you changed.)

- The addition of the missing `linux-amd64` natives for JOGL and gluegen is also great.

- Regarding `iconloader`, I feel conflicted. In principle it is a good thing if our own build of iconloader is specified by code, as you have done here, but I'm not sure the added complexity and build dependencies are worth it, given that it still doesn't eliminate all dependencies in `3rdpartypublic`. It also breaks the assumption that `fetchdeps` does not build anything. One idea is for us to fork iconloader on GitHub (in the micro-manager org) and add a `pom.xml` that works with [JitPack](https://jitpack.io/) (I checked existing forks but the only one that has a `pom.xml` is outdated).

**Comment by marktsuchida** [comment]
(Also one reason to handle iconloader the way I proposed is that we are hoping to stop using Ant (and Ivy) entirely in the future, switching to Maven proper: see #1392.)

**Comment by fabio-echegaray** [comment]
Hello Mark,

Thank you for the feedback. I have attended the comments regarding Ivy dependencies and removed the integration with Git now. It is compiling on Linux correctly; however I have no direct way to compile it under Windows or MacOS yet.

I will give JitPack a go.

**Comment by marktsuchida** [comment]
Perfect, thanks!

**Pull request merged**
