### PR TITLE
Studio: add more plugins to the ZMQ server search path.

### PR DESCRIPTION
**Pull request by nicost**
Downside is that starting the ZMQ server takes even more time.  Should we run this on a separate thread?

### CODE REVIEW

**Comment by nicost** [comment]
Second commit starts the ZMQ server on its own thread.  Seems to work, but I can not fully oversee the consequences.

**Comment by nicost** [comment]
On my system often 15-20 seconds.  It is a really annoying wait, especially if you are not planning on using pycromanager in this specific session.  I'll merge, we can revert if it leads to problems.

**Comment by henrypinkard** [comment]
Wow. Okay, I'll dig in there and see if I can get it to do something more intelligent

**Comment by nicost** [comment]
I tested a bit, and starting a Python script before the ZMQ server is ready does not seem to be a problem.  Moreover, and quite strangely, the server seems to respond quite quickly, way before the log message appears that the server is running.  This suggests there is something in the ZMQServer that takes a lot of time (but is not needed to get the Studio object active).

**Comment by nicost** [comment]
There is something weird, I believe in the ZMQ Server code. When I load a JavaObject for the first time, it takes about 3 minutes, and there is lots of output a tiny bit of which I copied below.  In the end, the object I asked for seems to work, although I there are problems when passing an object back in (I guess I should open a separate issue for that problem).  Any idea what is going on with the below output?

ng.Class.forName(Class.java:264)
	at org.micromanager.internal.zmq.ZMQUtil.getClassesFromDirectory(ZMQUtil.java:582)
	at org.micromanager.internal.zmq.ZMQUtil.getPackageClasses(ZMQUtil.java:499)
	at org.micromanager.internal.zmq.ZMQServer.getArgumentSignatures(ZMQServer.java:251)
	at org.micromanager.internal.zmq.ZMQServer.runConstructor(ZMQServer.java:318)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:465)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:116)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassNotFoundException: org.micromanager.internal.AcqControlDlg$2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.micromanager.internal.zmq.ZMQUtil.getClassesFromDirectory(ZMQUtil.java:582)
	at org.micromanager.internal.zmq.ZMQUtil.getPackageClasses(ZMQUtil.java:499)
	at org.micromanager.internal.zmq.ZMQServer.getArgumentSignatures(ZMQServer.java:251)
	at org.micromanager.internal.zmq.ZMQServer.runConstructor(ZMQServer.java:318)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:465)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:116)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassNotFoundException: org.micromanager.internal.AcqControlDlg$3
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.micromanager.internal.zmq.ZMQUtil.getClassesFromDirectory(ZMQUtil.java:582)
	at org.micromanager.internal.zmq.ZMQUtil.getPackageClasses(ZMQUtil.java:499)
	at org.micromanager.internal.zmq.ZMQServer.getArgumentSignatures(ZMQServer.java:251)
	at org.micromanager.internal.zmq.ZMQServer.runConstructor(ZMQServer.java:318)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:465)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:116)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassNotFoundException: org.micromanager.internal.AcqControlDlg$4$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.micromanager.internal.zmq.ZMQUtil.getClassesFromDirectory(ZMQUtil.java:582)
	at org.micromanager.internal.zmq.ZMQUtil.getPackageClasses(ZMQUtil.java:499)
	at org.micromanager.internal.zmq.ZMQServer.getArgumentSignatures(ZMQServer.java:251)
	at org.micromanager.internal.zmq.ZMQServer.runConstructor(ZMQServer.java:318)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:465)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:116)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassNotFoundException: org.micromanager.internal.AcqControlDlg$4
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.micromanager.internal.zmq.ZMQUtil.getClassesFromDirectory(ZMQUtil.java:582)
	at org.micromanager.internal.zmq.ZMQUtil.getPackageClasses(ZMQUtil.java:499)
	at org.micromanager.internal.zmq.ZMQServer.getArgumentSignatures(ZMQServer.java:251)
	at org.micromanager.internal.zmq.ZMQServer.runConstructor(ZMQServer.java:318)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:465)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:116)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassNotFoundException: org.micromanager.internal.AcqControlDlg$5
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.micromanager.internal.zmq.ZMQUtil.getClassesFromDirectory(ZMQUtil.java:582)
	at org.micromanager.internal.zmq.ZMQUtil.getPackageClasses(ZMQUtil.java:499)
	at org.micromanager.internal.zmq.ZMQServer.getArgumentSignatures(ZMQServer.java:251)
	at org.micromanager.internal.zmq.ZMQServer.runConstructor(ZMQServer.java:318)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:465)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:116)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassNotFoundException: org.micromanager.internal.AcqControlDlg$6
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.micromanager.internal.zmq.ZMQUtil.getClassesFromDirectory(ZMQUtil.java:582)
	at org.micromanager.internal.zmq.ZMQUtil.getPackageClasses(ZMQUtil.java:499)
	at org.micromanager.internal.zmq.ZMQServer.getArgumentSignatures(ZMQServer.java:251)
	at org.micromanager.internal.zmq.ZMQServer.runConstructor(ZMQServer.java:318)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:465)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:116)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassNotFoundException: org.micromanager.internal.AcqControlDlg$CheckBoxPanel$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.micromanager.internal.zmq.ZMQUtil.getClassesFromDirectory(ZMQUtil.java:582)
	at org.micromanager.internal.zmq.ZMQUtil.getPackageClasses(ZMQUtil.java:499)
	at org.micromanager.internal.zmq.ZMQServer.getArgumentSignatures(ZMQServer.java:251)
	at org.micromanager.internal.zmq.ZMQServer.runConstructor(ZMQServer.java:318)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:465)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:116)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassNotFoundException: org.micromanager.internal.AcqControlDlg$CheckBoxPanel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.micromanager.internal.zmq.ZMQUtil.getClassesFromDirectory(ZMQUtil.java:582)
	at org.micromanager.internal.zmq.ZMQUtil.getPackageClasses(ZMQUtil.java:499)
	at org.micromanager.internal.zmq.ZMQServer.getArgumentSignatures(ZMQServer.java:251)
	at org.micromanager.internal.zmq.ZMQServer.runConstructor(ZMQServer.java:318)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:465)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:116)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassNotFoundException: org.micromanager.internal.AcqControlDlg$ComponentTitledPanel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.micromanager.internal.zmq.ZMQUtil.getClassesFromDirectory(ZMQUtil.java:582)
	at org.micromanager.internal.zmq.ZMQUtil.getPackageClasses(ZMQUtil.java:499)
	at org.micromanager.internal.zmq.ZMQServer.getArgumentSignatures(ZMQServer.java:251)
	at org.micromanager.internal.zmq.ZMQServer.runConstructor(ZMQServer.java:318)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:465)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:116)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassNotFoundException: org.micromanager.internal.AcqControlDlg$LabelPanel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.micromanager.internal.zmq.ZMQUtil.getClassesFromDirectory(ZMQUtil.java:582)
	at org.micromanager.internal.zmq.ZMQUtil.getPackageClasses(ZMQUtil.java:499)
	at org.micromanager.internal.zmq.ZMQServer.getArgumentSignatures(ZMQServer.java:251)
	at org.micromanager.internal.zmq.ZMQServer.runConstructor(ZMQServer.java:318)
	at org.micromanager.internal.zmq.ZMQServer.parseAndExecuteCommand(ZMQServer.java:465)
	at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:116)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ClassNotFoundException: org.micromanager.internal.AcqControlDlg
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

**Comment by nicost** [comment]
Code to reproduce: 

```
studio = Studio()
ds = studio.data().create_ram_datastore()
#studio.displays().create_display(ds)
cb = studio.data().get_coords_builder()
for i in range (0, n):
    img = studio.live().snap(False)
    ds.put_image(img.get(0).copy_at_coords(cb.z(i).build()))
z_projector = JavaObject('org.micromanager.zprojector.ZProjectorPluginExecutor', args=[studio, ds])
new_store = studio.data().create_multipage_tiff_datastore(path + '\\' + name, True, True)
z_projector.project(new_store, True, "z", name, "z", 1, n, 0)
print('Done')

```

**Pull request merged**
